### ISSUE TITLE
Client Buildroot bringup on RaspberryPi

### ISSUE THREAD

**Issue by tanmay-mk** [cu-ecen-aeld/final-project-Amey2904dash#1]
**DoD:**

- [x]  Setup Buildroot on Client board (Raspberry Pi)

**Tasks:**

- [x]  Build Buildroot image on Raspberry Pi 3B
- [x]  Add SSH functionality.
- [x]  Verify login into Pi via SSH.

**Blocker:**

- [x]  Availability of Raspberry Pi
- [x]  Availability of SD Card to flash the Raspbian OS

**Comment by tanmay-mk** [comment]
Successfully built Buildroot image for Raspberry Pi, and logged in successfully using 'root' password. Check the bottom of the image to verify login with 'root'.
![Buildroot_Setup_Client](https://user-images.githubusercontent.com/89433097/161478219-2317d11f-b83e-418f-a59b-4000a69eee68.jpg)

References:
1. AESD Assignment 4 Part 2 instructions
2. Buildroot Assignments Base wiki pages

**Comment by tanmay-mk** [comment]
Successfully added SSH functionality to the client board. Following is the screenshot of the ifconfig command ran on the buildroot image. The ip address of the RPi is 10.0.0.170.
![IMG_20220403_205421](https://user-images.githubusercontent.com/89433097/161478408-ac045d13-2018-4c70-b24f-4605400aa067.jpg)

**Comment by tanmay-mk** [comment]
Successfully logged in to Raspberry Pi using remote SSH login.
![root login in pi](https://user-images.githubusercontent.com/89433097/161478493-1862f552-a54a-45a9-84d7-e557f37716c3.png)
