### ISSUE TITLE
Final Integration & Testing - Face Recognition on Buildroot and Sending data to Socket

### ISSUE THREAD

**Issue by tanmay-mk** [cu-ecen-aeld/final-project-Amey2904dash#13]
**DoD:**
Verify the output of Facial Recognition application on Buildroot and ensure that data sent by application is read from socket and sent to client successfully. Small part of https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/12.

**Tasks:**
- [x] Facial recognition software identifies the person and stores its name in a text file. 
- [x] Socket server application reads data from the text file in which data is stored by facial recognition application. 
- [x] Socket server application sends data successfully to client. 

**Blockers:**
No blockers identified.

**Comment by tanmay-mk** [comment]
Changed the facial recognition application so that instead of printing the person's name on terminal, it stores the name as a string in a text file 'names.txt' that is created using a startup script dynamically during boot-up time. 
Startup script : [Link](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/main/base_external/rootfs_overlay/etc/init.d/S99initmodules), Check [this](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/fdf971b5ef6354df6651257c53abc2865cce51c2/base_external/rootfs_overlay/etc/init.d/S99initmodules#L14) & [this](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/fdf971b5ef6354df6651257c53abc2865cce51c2/base_external/rootfs_overlay/etc/init.d/S99initmodules#L15).

Changing the permission of these files. [Link](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/fdf971b5ef6354df6651257c53abc2865cce51c2/base_external/rootfs_overlay/etc/init.d/S99initmodules#L16)

**Comment by tanmay-mk** [comment]
Facial recognition application recognizes the face and stores the name of the person in a text file in /etc/face-rec-sample/names.txt file. 
![1](https://user-images.githubusercontent.com/89433097/165446866-f90f4cd2-b573-4cea-9168-b166e64517ed.png)

**Comment by tanmay-mk** [comment]
Even if the same person comes in front of the camera multiple times, their name will only be stored in the file once to avoid repetition. If the camera recognizes the same person again, it will print "<name of person> is already present" on the screen. 
 
![WhatsApp Image 2022-04-26 at 11 17 26 PM](https://user-images.githubusercontent.com/89433097/165447145-0f355c8c-486c-4a64-9c6f-43f29bdb296f.jpeg)

**Comment by tanmay-mk** [comment]
The [socket_server](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/blob/main/sample_socket/socket_server/socket_server.c) application [reads](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/blob/4c9384774894fefce9ad36e23d1525f1ccf7061d/sample_socket/socket_server/socket_server.c#L56) the stored name from the file and sends it to client over socket. The socket server waits indefinitely until there is more data available in the text file and sends it immediately as soon as new data (in this case, new person's name) to client.

**Comment by tanmay-mk** [comment]
For debugging, the socket server application prints the sent data byte-by-byte on terminal. So we can visually examine the data sent over socket. 
![2](https://user-images.githubusercontent.com/89433097/165447625-7456a603-d598-43e3-a08b-187baece5439.jpeg)

**Comment by tanmay-mk** [comment]
Latest code for facial recognition is [here](https://github.com/cu-ecen-aeld/final-project-tanmay-mk). 
Commit number: 128d63865b601ff3e8e76dd2ce60a368b7a2e51b & [Link] (https://github.com/cu-ecen-aeld/final-project-tanmay-mk/commit/128d63865b601ff3e8e76dd2ce60a368b7a2e51b)
