### ISSUE TITLE
Final Integration & Testing - Reading temperature from TMP102 continuously and Sending data to Socket

### ISSUE THREAD

**Issue by tanmay-mk** [cu-ecen-aeld/final-project-Amey2904dash#14]
**DoD:**
Verify the output of temperature sensor (TMP102) application using I2C on Buildroot and ensure that data sent by application is read from socket and sent to client successfully. Small part of https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/12.

**Tasks:**
- [x] I2C is enabled by a startup script stored in /etc/init.d
- [x] Buildroot recognizes I2C device. 
- [x] Temperature value is read by sensor and recorded in a text file temp.txt
- [x] Socket server application sends data successfully to client. 

**Blockers:**
No blockers identified.

**Comment by Amey2904dash** [comment]
I2C modules are successfully loaded in the startup script at path /etc/init.d/ for values are loaded into the text file for transmitting over the socket communication to client pi.
![image](https://user-images.githubusercontent.com/89843479/165474408-70aa43b0-3805-47f0-a43a-b2eaa14efe98.png)

**Comment by Amey2904dash** [comment]
I2C application recognizes the updated temperature values in a text file in /etc/face-rec-sample/temp.txt file.
![image](https://user-images.githubusercontent.com/89843479/165476159-c8bbb5a8-7d15-4fdf-b3e8-4aac491657b6.png)

**Comment by Amey2904dash** [comment]
Successfully sent and received data over Bluetooth using BlueZ stack on RPI client and android EFR connect application with custom name, service and characteristics as shown in below figure
![WhatsApp Image 2022-04-27 at 12 50 02 AM (1)](https://user-images.githubusercontent.com/89843479/165477190-c6ba48a1-78ae-49f8-9a23-f370e0446d4d.jpeg)
:
![1](https://user-images.githubusercontent.com/89843479/165477241-a84e6154-96d5-4161-88d9-45cec1436a44.jpg)

**Comment by Amey2904dash** [comment]
Latest code commit #: da5eed756445007f8db098215f03fe0a2ba8abd9
Link: https://github.com/cu-ecen-aeld/final-project-varun2506/commit/da5eed756445007f8db098215f03fe0a2ba8abd9

**Comment by varun2506** [comment]
I2C modules are successfully loaded in the startup script at path /etc/init.d/ for values are loaded into the text file for transmitting over the socket communication to client pi.
![image](https://user-images.githubusercontent.com/89843479/165474408-70aa43b0-3805-47f0-a43a-b2eaa14efe98.png)

**Comment by varun2506** [comment]
I2C application recognizes the updated temperature values in a text file in /etc/face-rec-sample/temp.txt file.
![image](https://user-images.githubusercontent.com/89843479/165476159-c8bbb5a8-7d15-4fdf-b3e8-4aac491657b6.png)

**Comment by varun2506** [comment]
Data is sent over the socket server and temperature string is displayed on client LCD.
![WhatsApp Image 2022-04-27 at 12 49 39 AM](https://user-images.githubusercontent.com/89843479/165476758-d4dd50c4-da4d-44ab-8472-bc7a9fede9d0.jpeg)

**Comment by varun2506** [comment]
Successfully sent and received data over Bluetooth using BlueZ stack on RPI client and android EFR connect application with custom name, service and characteristics as shown in below figure
![WhatsApp Image 2022-04-27 at 12 50 02 AM (1)](https://user-images.githubusercontent.com/89843479/165477190-c6ba48a1-78ae-49f8-9a23-f370e0446d4d.jpeg)


![1](https://user-images.githubusercontent.com/89843479/165477241-a84e6154-96d5-4161-88d9-45cec1436a44.jpg)

**Comment by varun2506** [comment]
Latest code commit #: da5eed756445007f8db098215f03fe0a2ba8abd9
Link: https://github.com/cu-ecen-aeld/final-project-varun2506/commit/da5eed756445007f8db098215f03fe0a2ba8abd9

**Comment by varun2506** [comment]
Final Application Setup
![WhatsApp Image 2022-04-27 at 12 50 02 AM](https://user-images.githubusercontent.com/89843479/165483273-981e6d61-88c3-4d02-9e96-4032b1f08d3e.jpeg)
