### ISSUE TITLE
Final Integration & Testing - Reading data from Facial recognition application & Temperature sensor application and sending it to client over socket

### ISSUE THREAD

**Issue by tanmay-mk** [cu-ecen-aeld/final-project-Amey2904dash#15]
**DoD:**
1. Create a small data packet of the data read from temp.txt and names.txt and send it to client using socket.
2. Once client receives the data, print the received data on 16x4 LCD Display. (Name on first row, temperature on second row)  
Small part of https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/12.

**Tasks:**
- [x] Read data from names.txt (Data stored by facial recognition application)
- [x] Read data from temp.txt (Data stored by temperature sensor application)
- [x] Create a small data packet and send it to client using socket.
- [x] Socket client application receives packet and reads the data.
- [x] Socket client application prints the data on 16x4 LCD Display.

**Blockers:**
No blockers identified.

**Comment by Amey2904dash** [comment]
Successfully read data from two text files having the two sensors data ( camera and temperature sensor

1. Camera Data - 
![image](https://user-images.githubusercontent.com/89843479/165481915-e0fe22c5-376f-41f1-84db-2a87e29480a7.png)

2. Temperature Data - 
![image](https://user-images.githubusercontent.com/89843479/165482156-d3b978e4-ceb0-418a-906d-88cb92bf0da2.png)

**Comment by Amey2904dash** [comment]
Successfully created a data packet and integrating it into the application for socket communication.

![image](https://user-images.githubusercontent.com/89843479/165482606-af30fd19-afe4-42b2-9662-fced44de19a6.png)

**Comment by Amey2904dash** [comment]
Successfully received the data on client pi via socket communication and displayed the data on the LCD display.
![WhatsApp Image 2022-04-27 at 12 50 24 AM](https://user-images.githubusercontent.com/89843479/165483004-49a2a4cb-bea6-44d1-8172-9f022d49e4ed.jpeg)

**Comment by Amey2904dash** [comment]
Final Application Setup
![WhatsApp Image 2022-04-27 at 12 50 02 AM](https://user-images.githubusercontent.com/89843479/165483273-981e6d61-88c3-4d02-9e96-4032b1f08d3e.jpeg)

**Comment by Amey2904dash** [comment]
Latest Code Commit is [here](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/commit/a2ca163fa1b7f2331cdcc55ff2b5164ea5296f31)
Commit Number- a2ca163fa1b7f2331cdcc55ff2b5164ea5296f31
